<?php

namespace ContainerQGayi6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I09SeM3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i09SeM3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i09SeM3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'skill' => ['privates', '.errored..service_locator.i09SeM3.App\\Entity\\Skill', NULL, 'Cannot autowire service ".service_locator.i09SeM3": it references class "App\\Entity\\Skill" but no such service exists.'],
            'skillRepository' => ['privates', 'App\\Repository\\SkillRepository', 'getSkillRepositoryService', true],
        ], [
            'skill' => 'App\\Entity\\Skill',
            'skillRepository' => 'App\\Repository\\SkillRepository',
        ]);
    }
}
