<?php

namespace ContainerQGayi6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STzgHXGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.STzgHXG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.STzgHXG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService', true],
            'seanceRepository' => ['privates', 'App\\Repository\\SeanceRepository', 'getSeanceRepositoryService', true],
        ], [
            'mailer' => '?',
            'seanceRepository' => 'App\\Repository\\SeanceRepository',
        ]);
    }
}
