<?php

namespace ContainerQqu2e4I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkill2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i09SeM3.App\Entity\Skill' shared service.
     *
     * @return \App\Entity\Skill
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i09SeM3": it references class "App\\Entity\\Skill" but no such service exists.');
    }
}
